# Generated by Django 4.2.16 on 2026-05-11 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timelogs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task', 'user'], name='timelogs_task_id_6446c9_idx'), models.Index(fields=['user', 'started_at'], name='timelogs_user_id_13979a_idx')],
            },
        ),
    ]
